# This is a basic workflow to help you get started with Actions

name: RunCucumberWorkflowDispatch

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout master branch from Github
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      
      - name: Install Maven
        run: mvn -B package --file pom.xml
      
      - name: List the current directory
        run: ls -a
      
      # Runs a set of commands using the runners shell  
      - name: What is in target directory?
        run: |
          cd target
          ls -a
     
      - name: User Actor Email
        run: 'echo "User Actor: ${{ github.actor }}"'
          
      
      # Access the sent value from postman
      - name: Read the input value from postman
        run: 'echo "Event text: ${{ github.event.client_payload.example-key }}"'

      - name: Build with Maven
        env:
          GITHUB_RUN_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          TEST_ORDERNUM: ${{ github.event.inputs.ordernumber }}
        #run: mvn test -Dtest=TestRunner
        run: >
          mvn test -Dtest=TestRunner
          --define cucumber.filter.tags=@web-navigation-test
      
